# Generated by Django 3.1.13 on 2022-03-01 09:42

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='name')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(18.0)], verbose_name='price')),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
                'ordering': ['dish_category__option_number'],
            },
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('name', models.CharField(default='', max_length=250, verbose_name='name')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('option_number', models.PositiveIntegerField(help_text='This number must be between 1 and 11.', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='option number')),
            ],
            options={
                'verbose_name': 'dish category',
                'verbose_name_plural': 'dish categories',
                'ordering': ['option_number'],
            },
        ),
        migrations.CreateModel(
            name='MealSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='name')),
                ('start_time', models.TimeField(default=datetime.time(0, 0), verbose_name='start time')),
                ('end_time', models.TimeField(default=datetime.time(0, 0), verbose_name='end time')),
                ('offplan_time', models.TimeField(default=datetime.time(0, 0), verbose_name='offplan time')),
                ('report_time', models.TimeField(default=datetime.time(0, 0), verbose_name='report time')),
                ('is_payment', models.BooleanField(default=False, verbose_name='is payment')),
            ],
            options={
                'verbose_name': 'meal schedule',
                'verbose_name_plural': 'meals schedules',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('date', models.DateField(verbose_name='date')),
                ('diet_dishes', models.ManyToManyField(related_name='diet_menu', to='reservation.Dish', verbose_name='diet dishes')),
                ('dishes', models.ManyToManyField(to='reservation.Dish', verbose_name='dishes')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.mealschedule', verbose_name='schedule')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'ordering': ['-date', '-schedule__id'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'operation',
                'verbose_name_plural': 'operations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('person', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='person')),
                ('person_donate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='donate')),
                ('reserv_log_user', models.CharField(default='', max_length=250, verbose_name='reserved by')),
                ('confirm_log_user', models.CharField(default='', max_length=250, verbose_name='confirmed by')),
                ('offplan_data', django_extensions.db.fields.json.JSONField(default=[], verbose_name='offplan information')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='is confirmed')),
                ('dishes', models.ManyToManyField(to='reservation.Dish', verbose_name='dishes')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.menu', verbose_name='menu')),
                ('modify_log_user', models.ManyToManyField(blank=True, to='reservation.User', verbose_name='updated by')),
                ('operations', models.ManyToManyField(blank=True, to='reservation.Operation', verbose_name='operations')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'ordering': ['-id'],
                'permissions': (('all_view_reservation', 'Can view all reserves'), ('area_view_reservation', 'Can view all reserves from same area'), ('all_add_reservation', 'Can add all reserves'), ('area_add_reservation', 'Can add all reserves from same area'), ('all_change_reservation', 'Can change all reserves'), ('confirm_change_reservation', 'Can change all reserves from the day'), ('area_change_reservation', 'Can change all reserves from same area'), ('all_delete_reservation', 'Can delete all reserves'), ('area_delete_reservation', 'Can delete all reserves from same area'), ('view_report', 'Can view report'), ('view_operation', 'Can view operation')),
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.dishcategory', verbose_name='dish category'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('person', 'menu'), name='unique reservation'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('date', 'schedule'), name='unique menu'),
        ),
    ]
