# Generated by Django 3.1.13 on 2022-03-01 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'reservation category',
                'verbose_name_plural': 'reservation categories',
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='person'),
        ),
        migrations.CreateModel(
            name='ReservCatSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_diners', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='count diners')),
                ('mealschedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.mealschedule', verbose_name='schedule')),
                ('reservation_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservationcategory', verbose_name='reservation category')),
            ],
            options={
                'verbose_name': 'meal schedule',
                'verbose_name_plural': 'meals schedules',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='reservationcategory',
            name='meal_schedules',
            field=models.ManyToManyField(through='reservation.ReservCatSchedule', to='reservation.MealSchedule'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservationcategory', verbose_name='reservation category'),
        ),
        migrations.AddConstraint(
            model_name='reservcatschedule',
            constraint=models.UniqueConstraint(fields=('mealschedule', 'reservation_category'), name='unique category'),
        ),
    ]
