# Generated by Django 3.1.13 on 2022-05-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220301_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcategory',
            name='dining_room',
            field=models.IntegerField(blank=True, null=True, verbose_name='dining room'),
        ),
    ]
