# Generated by Django 3.1.14 on 2022-06-06 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservationcategory_dining_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcategory',
            name='option_number',
            field=models.PositiveIntegerField(help_text='Este número debe estar entre 1 y 11.', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='option number'),
        ),
    ]
