# Generated by Django 3.1.14 on 2022-07-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20220606_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservcatschedule',
            options={'ordering': ['mealschedule__id'], 'verbose_name': 'meal schedule', 'verbose_name_plural': 'meals schedules'},
        ),
        migrations.AddField(
            model_name='reservcatschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
