# Generated by Django 3.1.13 on 2022-07-15 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20220711_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcategory',
            name='is_confirmable',
            field=models.BooleanField(default=False, verbose_name='confirmable'),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='option_number',
            field=models.PositiveIntegerField(help_text='This number must be between 1 and 11.', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='option number'),
        ),
    ]
