# Generated by Django 4.1.2 on 2022-10-12 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20220715_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcategory',
            name='option_number',
            field=models.PositiveIntegerField(help_text='Este número debe estar entre 1 y 11.', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='option number'),
        ),
    ]
