# Generated by Django 4.1.2 on 2022-07-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_dishcategory_option_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-id'], 'permissions': (('all_view_reservation', 'Can view all reserves'), ('area_view_reservation', 'Can view all reserves from same area'), ('all_add_reservation', 'Can add all reserves'), ('area_add_reservation', 'Can add all reserves from same area'), ('all_change_reservation', 'Can change all reserves'), ('confirm_change_reservation', 'Can change all reserves from the day'), ('area_change_reservation', 'Can change all reserves from same area'), ('all_delete_reservation', 'Can delete all reserves'), ('area_delete_reservation', 'Can delete all reserves from same area'), ('view_report', 'Can view report'), ('view_operation', 'Can view operation'), ('view_camera', 'Can view camera')), 'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
    ]
