# Generated by Django 4.1.4 on 2022-12-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_dish_id_alter_mealschedule_id_alter_menu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='reservation',
            field=models.IntegerField(null=True),
        ),
    ]
