# Generated by Django 4.1.4 on 2022-12-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_prueba_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
    ]
