# Generated by Django 4.1.4 on 2022-12-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_prueba_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='operations',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
