# Generated by Django 4.1.4 on 2022-12-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_remove_reservation_operations_delete_operation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prueba',
            new_name='Operation',
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Operation', 'verbose_name_plural': 'Operation'},
        ),
    ]
