# Generated by Django 4.1.4 on 2024-03-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_rename_prueba_operation_alter_operation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-id'], 'permissions': (('all_view_reservation', 'Can view all reserves'), ('area_view_reservation', 'Can view all reserves from same area'), ('all_add_reservation', 'Can add all reserves'), ('area_add_reservation', 'Can add all reserves from same area'), ('all_change_reservation', 'Can change all reserves'), ('confirm_change_reservation', 'Can change all reserves from the day'), ('area_change_reservation', 'Can change all reserves from same area'), ('all_delete_reservation', 'Can delete all reserves'), ('area_delete_reservation', 'Can delete all reserves from same area'), ('view_report', 'Can view report'), ('view_operation', 'Can view operation'), ('view_camera', 'Can view camera'), ('confirm_after_hours', 'Can confirm after hours')), 'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
    ]
